version: '3'
services:
    client:
        container_name: client
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - "/usr/app/node_modules"
            - "./:/usr/app"